config/routes.rb
Rails.application.routes.draw do
	get 'confirmation_page' => 'feeds#confirmation_page'
	get 'home/index' => 'feeds#home'
	resources :feeds
	resources :users, path: '/portal'
	resources :portals, path: '/#portal'
	
	devise_for :admins
	
	devise_scope :admin do
		authenticated :admin do
			get 'admins/sign_out' => 'devise/sessions#destroy'
		end

		unauthenticated do
			get 'admins/sign_in' => 'devise/sessions#new'
		end
	end
	
	devise_for :users, :controllers => { registrations: 'registrations' }
	
	devise_scope :user do
		authenticated :user do
			get '/users' => 'devise/registrations#edit'
			get 'users/sign_out' => 'devise/sessions#destroy'
			root to: "feeds#index", as: :authenticated_root
		end
		unauthenticated do
			get 'confirmation_page' => 'feeds#confirmation_page'
			get 'users/sign_in' => 'devise/sessions#new'
			get '/users' => 'devise/registrations#new'
			root to: 'feeds#home', as: :unauthenticated_root
		end
	end

end

app/models/feed.rb
class Feed < ActiveRecord::Base
	belongs_to :user
  	mount_uploader :image, ImageUploader
  	after_save :change_publishing
	validate :checking_feed_text
	validate :checking_for_date
	validate :checking_for_image_size

	private

	def change_publishing
		if User.find(self[:user_id]).permissions == 100
			publishing = false
			UserMailer.new_feed(self).deliver_later
		end	
	end

	def checking_for_image_size
		if image.size > 300.kilobytes
			errors[:base] = "L\'immagine non può superare 300 Kb"
		end
	end

	def checking_feed_text
		if !(text_ita.present? and text_eng.present?)
			errors[:base] = "Non puoi pubblicare feed vuoti!"
		elsif image.present? and text_ita.size > 101 and text_eng > 101
			errors[:base] = "I feeds con immagini non possono contenere più di 101 caratteri!"
		elsif text_ita.size > 124 || text_eng.size > 124
			errors[:base] = "I feeds non possono contenere più di 124 caratteri!"
		end
	end

	def checking_for_date
		if !(date.present?)
			errors[:base] = "E\' necessario inserire una data di pubblicazione per il feed!"
		elsif date.utc <= DateTime.now.utc
			errors[:base] = "La data di pubblicazione non può essere nel passato!"
		end
	end
end

app/controllers/feeds_controller.rb
require 'google/api_client'
require 'json'

class FeedsController < ApplicationController
	before_action :set_feed, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:home, :confirmation_page]
	around_filter :user_time_zone, :if => :current_user

	def home
		@feeds = Feed.all
	end

	def confirmation_page	
	end

	def index
		@feeds = Feed.all
	end


	def show
	end

	def new
		@feed = Feed.new
	end

	def edit
	end

	def create
		@feed = Feed.new(feed_params)
		@feed.user_id = current_user.id
			# Translate from the original Italian text to English via Google Translate APIs in production mode
		if Rails.env.production?
			feed_text_english = translate_feed(@feed.text_ita)
				if !(feed_text_english.blank?)
					if @feed.image.blank?
						if feed_text_english.size > 126
							feed_text_english = feed_text_english.slice(0, 123) + '...'
							flash[:notice] = 'Il feed inglese è stato abbreviato perchè superava il limite di caratteri'
						end
					elsif feed_text_english.size > 101
						feed_text_english = feed_text_english.slice(0, 98) + '...'
						flash[:notice] = 'Il feed inglese è stato abbreviato perchè superava il limite di caratteri'
					else
						flash[:notice] = 'Entrambi i feeds sono stati aggiornati con successo'
					end
				end
				@feed.text_eng = feed_text_english.gsub("\xE2\x80\x8B", "")
		else
			@feed.text_eng = 'Hi there! Write here the english traslation'
		end
			respond_to do |format|			
				if @feed.save
					format.html { render :edit, notice: 'Il feed è stato creato!' }
					format.json { render :show, status: :created, location: @feed }
				else
				format.html { render :new }
				format.json { render json: @feed.errors, status: :unprocessable_entity }
				end
			end
	end

	def update
		respond_to do |format|
			if @feed.user_id == current_user.id && @feed.update(feed_params)
					if @feed.text_eng.blank?
						flash[:notice] = 'Il feed Italiano è stato aggiornato con successo'
					else
						if @feed.image.blank?
							if @feed.text_eng.size > 124
								@feed.text_eng = @feed.feed_text_english.slice(0, 121) + '...'
								flash[:notice] = 'Il feed inglese è stato abbreviato perchè superava il limite di caratteri'
							end
						elsif @feed.text_eng.size > 101
							@feed.feed_text_english = @feed.feed_text_english.slice(0, 98) + '...'
							flash[:notice] = 'Il feed inglese è stato abbreviato perchè superava il limite di caratteri'
						else
							flash[:notice] = 'Entrambi i feeds sono stati aggiornati con successo'
						end
					end
				format.html { redirect_to feeds_path }
				format.json { render :show, status: :ok, location: @feed }
			else
				format.html { redirect_to feeds_url }
				format.json { render json: @feed.errors, status: :unprocessable_entity }
				flash[:notice] = 'Non puoi modificare questo feed'
			end
		end
	end

	def destroy
		respond_to do |format|
			if (@feed.user_id == current_user.id) && @feed.destroy				
				format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
				format.json { head :no_content }
			else
				format.html { redirect_to feeds_url }
				format.json { render json: @feed.errors, status: :unprocessable_entity }
				flash[:notice] = 'Non puoi distruggere questo feed'
			end
		end
	end

	private

# Use Google Translate APIs to translate feed text from the original Italian to English
	def translate_feed(text_ita)
		google_client = Google::APIClient.new(
			:application_name => APP_CONFIG['google']['production']['application_name'],
			:key => APP_CONFIG['google']['production']['key'],
			:application_version => '1.0.0',
			:authorization => nil
		)
		
		# Load client secrets from your client_secrets.json
		# NOT needed for the Google Translate APIs
		# client_secrets = Google::APIClient::ClientSecrets.load
		
		translate = google_client.discovered_api('translate', 'v2')
		
		result = google_client.execute(
			:api_method => translate.translations.list,
			:parameters => {
				'format' => 'text',
				'source' => 'it',
				'target' => 'en',
				'q' => text_ita
			}
		)
		
		parsed = JSON.parse(result.data.to_json)
		
		# Example of data returned
		# {"translations":[{"translatedText":"This is a pen"}]}'
		
		english_translation = parsed["translations"][0]["translatedText"]
		
		# TODO: return a warning if the translation is over 140 characters (or whatever limit we have)

		return english_translation
	end
	# translate_feed end #
	def set_feed
		@feed = Feed.find(params[:id])
	end

	def feed_params
		params.require(:feed).permit(:user_id, :text_ita, :text_eng, :image, :date, :publishing)
	end

	def user_time_zone(&block)
		if params[:locale] == "en"
			Time.use_zone("GMT", &block)
		else
			Time.use_zone("CET", &block)
		end
	end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_doubleForm.html.erb
	<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>
      <ul>
      <% @feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
		<div class="background">
			<table>
				<tr>
					<th colspan="2">
					<%= f.text_area :text_ita, :class => "textBox", :onkeyup => 'textCounter(this, "charCounterIta");', :placeholder => "Scrivi qui il testo del tuo feed ..." %>
					</th>
				</tr>
				
				<tr>
					<th id="charCounterIta" align="left" width="50%"></th>
					<th id="charCounterEng" align="right" width="50%"></th>
				</tr>
				
				<tr>
					<th colspan="2">
					<%= f.text_area :text_eng, :class => "textBox", :onkeyup => 'textCounter(this, "charCounterEng");', :placeholder => "Scrivi qui la versione inglese del feed ..." %>
					</th>
				</tr>
				
				<tr>
					<th colspan="2">Data e ora di pubblicazione:</th>
				</tr>
				
				<tr>
					<th colspan="2"><%= f.datetime_select :date, :minute_step => 15 %></th>
				</tr>
				
				<tr>
					<th colspan="2">Inserisci un'immagine:</th>
				</tr>
				
				<tr>
					<th colspan="2"><%= f.file_field :image %></th>
				</tr>
				
				<tr>
					<th colspan="2"><input type="submit" value="Conferma" class="button"/></th>
				</tr>
			</table> 
		</div>
	<% end %>

app/views/feeds/_form.html.erb
<%= content_for :head do %>
<% end %>

<%= content_for :body do %>
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>
      <ul>
      <% @feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text_ita %><br>
    <%= f.text_field :text_ita %>
  </div>
  <div class="field">
    <%= f.label :text_eng %><br>
    <%= f.text_field :text_eng %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date, :minute_step => 15  %>
  </div>
  <div class="field">
	<%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<% end %>

app/views/feeds/confirmation_page.en.html.erb
<% content_for :head do %>
	<title>Confirmation page</title>
<% end %>	

<% content_for :body do %>
	<!-- START bar -->
			<div id="home" class="bar" style="font-size:10px;">
				<div id="link">
						<ul>
							<li><a href="/">Home</a></li>
							<li><a href="<%= new_user_session_path %>" name="Hlink">Sign in</a></li>
							<li><a href="<%= new_user_registration_path %>" name="Hlink">Sign up</a></li>
							<li>
								<%= link_to(confirmation_page_path(:locale=>'it')) do %>
									<%= image_tag("IT_flag.png") %> 
								<% end %>
								<%= link_to(confirmation_page_path(:locale=>'en')) do %>
									<%= image_tag("UK_flag.png") %>
								<% end %>
							</li>
						</ul>
				</div>
				<span id="bar_text">
					 The first world war
				</span>
			</div>
		<!-- END bar -->
<% end %>	

app/views/feeds/confirmation_page.it.html.erb
<% content_for :head do %>
	<title>Confirmation page</title>
<% end %>	

<% content_for :body do %>
	<!-- START bar -->
			<div id="home" class="bar" style="font-size:10px;">
				<div id="link">
						<ul>
							<li><a href="/">Home</a></li>
							<li><a href="<%= new_user_session_path %>" name="Hlink">Sign in</a></li>
							<li><a href="<%= new_user_registration_path %>" name="Hlink">Sign up</a></li>
							<li>
								<%= link_to(confirmation_page_path(:locale=>'it')) do %>
									<%= image_tag("IT_flag.png") %> 
								<% end %>
								<%= link_to(confirmation_page_path(:locale=>'en')) do %>
									<%= image_tag("UK_flag.png") %>
								<% end %>
							</li>
						</ul>
				</div>
				<span id="bar_text">
					 The first world war
				</span>
			</div>
		<!-- END bar -->
<% end %>	

app/views/feeds/edit.html.erb
<%= content_for :head do %>
<% end %>

<%= content_for :body do %>
	<h1> Modifica il tuo feed </h1>

	<% if @feed.image.present? %>
		<div id="<%= @feed.id %>" onclick="Expand_Image(<%= @feed.id %>)" class="feedImage">
		<%= image_tag(@feed.image_url) %>
		</div>
	<% end %>
	
	<%= render 'doubleForm' %>

	<p id='notice'> <%= @error %> </p>
 |
	<%= link_to 'Back', feeds_path %>

<% end %>

app/views/feeds/home.en.html.erb
	<%= content_for :head do %>
		
		<link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
		<link href="/assets/normalize.css" rel="stylesheet" />
		<link href="/assets/jquery.bxslider.css" rel="stylesheet" />
		<link href='http://fonts.googleapis.com/css?family=Tangerine' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Raleway:400,300' rel='stylesheet' type='text/css'>
		<link href="/assets/modal.css" rel="stylesheet" type="text/css">
		<link href="/assets/index_style.css" rel="stylesheet" type="text/css">
		
		<script data-turbolinks-track="true" src="/assets/jquery.js?body=1"></script>
		<script data-turbolinks-track="true" src="/assets/jquery_ujs.js?body=1"></script>
		<script data-turbolinks-track="true" src="/assets/turbolinks.js?body=1"></script>
		
		<script src="/assets/jquery_index.min.js"></script>
	<% end %>

	<%= content_for :body do %>
		<div id="wrapper_x">
			<% @LastFeeds = @feeds.last(3).reverse %>
			<!-- All modals added here for the demo. You would of course just have one, dynamically created -->
			<div class="md-modal md-effect-1" id="modal-1">
				<div class="md-content">
					<h3>#TheFirstWorldWar</h3>
					<div>
						<ul>
							<% if !@LastFeeds[0].blank? %>
							<li>"<%= @LastFeeds[0].text_ita %>"<% if user = User.find_by(id: params[@LastFeeds[0].user_id]) %><%= user.name %><% end %>(<%= @LastFeeds[0].date.strftime('%d/%m/%Y') %>)</li>
						<% end %>
						<% if !@LastFeeds[1].blank? %>
							<li>"<%= @LastFeeds[1].text_ita %>"<% if user = User.find_by(id: params[@LastFeeds[1].user_id]) %><%= user.name %><% end %>(<%= @LastFeeds[1].date.strftime('%d/%m/%Y') %>)</li>
						<% end %>
						<% if !@LastFeeds[2].blank? %>
							<li>"<%= @LastFeeds[2].text_ita %>"<% if user = User.find_by(id: params[@LastFeeds[2].user_id]) %><%= user.name %><% end %>(<%= @LastFeeds[2].date.strftime('%d/%m/%Y') %>)</li>
						<% end %>
						</ul>
						
						<div class="popup_social_text">
							Follow our news <a href="https://www.facebook.com/pages/La-Grande-Guerra-in-tempo-reale/311104819049617">Facebook</a> o <a href="https://twitter.com/lagrandeguerra">Twitter</a>
						</div>
						<button class="md-close">Close</button>
					</div>
				</div>
			</div>
			<!-- START bar -->
			<div id="home" class="bar">
				<div id="link">
						<ul>
							<li><a href="#team">Team</a></li>
							<li><a href="#feed">Feed</a></li>
							<li><a href="<%= new_user_session_path %>" name="Hlink">Sign in</a></li>
							<li><a href="<%= new_user_registration_path %>" name="Hlink">Sign up</a></li>
							<li>
								<%= link_to(home_index_path(:locale=>'it')) do %>
									<%= image_tag("IT_flag.png") %> 
								<% end %>
								<%= link_to(home_index_path(:locale=>'en')) do %>
									<%= image_tag("UK_flag.png") %>
								<% end %>
							</li>
							</li>
						</ul>
				</div>
				<span id="bar_text">
					 The First World War
				</span>
			</div>
			<!-- END bar -->
			
			<section id="first">
				<div style="display:table;">
					<div class="table">
						<h1 id="first_left_text">
							Welcome to Ragazzidel99.it
						</h1>
						<div id="first_left_text_und">
							The First World War
						</div>
						</div>
					
					<div id="first_left_text_exp">
							100 years ago one of the most cruel tragedy the history remember occurred. At the same time this caused the liberation of Italy from strangers. This happens thanks to the sacrifice of a generation of guys.
					</div>
					<a href="#feed">
						<div class="button_b_w">
							More about us
						</div>
					</a>
				</div>
			</section>
			<section id="feed">
				<div id="feed_collage_section">
					<div id="second_image_position_test">
						<%= image_tag("collage.png") %>
					</div>
					<div id="feed_preview">
						<%= image_tag("collage_feed.png") %>
					</div>
					<div id="second_text">
						Ragazzidel99 describes day by day about the first great war, with news and picture.
					</div>
				</div>
				<div class="second_social">
					<div class="second_single_social" style="padding-right:100px;">
						<div id="second_feed_preview_text">
							For a preview of the picture:
						</div>
						<!--<div class="button_b_w" style="margin:10px auto 0 auto;">
							CLICCA QUI
						</div>-->
						<button class="md-trigger" data-modal="modal-1">Click here!</button>
					</div>
					<a href="https://www.facebook.com/pages/La-Grande-Guerra-in-tempo-reale/311104819049617">
						<div class="second_single_social" style="padding-right:100px;">
							<%= image_tag("facebook-icon-128.png") %>
							<span id="second_text_fb">
								/ww1fromitaly
							</span>
						</div>
					</a>
					<a href="https://twitter.com/lagrandeguerra">
						<div class="second_single_social">
								<%= image_tag("twitter-icon-128.png") %>
								<span id="second_text_twitter">
									@ww1fromitaly
								</span>
						</div>
					</a>
				</div>
			</section>
			
			<!-- SECTION chi siamo -->
			<div class="who" id="team">
				<h3>Credits</h3>
				<div id="first_who_section">
					
					<div class="vincenzo">
							<img alt="Vincenzo Di Nicola" src="<%= asset_path 'vincenzo.jpg' %>">
							<h2>Vincenzo Di Nicola</h2>
							<a href="https://twitter.com/vincenzo" class="twitter-follow-button" data-show-count="false">Follow @vincenzo</a>
							<script>
								!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
							</script>
							<h4>Adminastrator</h4>
							<p>Teramo (TE) <br>Year 1979</p>  
					</div>
					
					<div class="liceoscientifico">
						<img alt="Liceo Scientifico Albert Einstein" src="<%= asset_path 'einstein.jpg' %>">
						<h2>High School Albert Einstein</h2>
						<h2>Teramo - Abruzzo</h2>
					</div>
				</div>
				
				<div style="padding-left:7em;margin-left:8em">
					<div class="member">
						<img alt="Davide Di Carlo" src="<%= asset_path 'dadda_dc.jpg' %>">
						<h2>Davide Di Carlo</h2>
						<h4>developer</h4>
						<p>Teramo (TE)<br>year 1997</p>
					</div>
					
					<div class="member">
						<img alt="Federico Pomponii" src="<%= asset_path 'pomponii.jpg' %>">
						<h2>Federico Pomponii</h2>
						<h4>developer</h4>
						<p>Canzano (TE)<br>year 1997</p>
					</div>
					
					<div class="member">
						<img alt="Davide Barbieri" src="<%= asset_path 'dadda_b.jpg' %>">
						<h2>Davide Barbieri</h2>
						<h4>developer</h4>
						<p>Teramo (TE)<br>year 1997</p>
					</div>
					
					<div class="member">
						<img alt="Lorenzo Camaione" src="<%= asset_path 'lorenzo_c.jpg' %>">
						<h2>Lorenzo Camaione</h2>
						<h4>developer</h4>
						<p>Teramo (TE)<br>year 1996</p>
					</div>
					
					<div class="member">
						<img alt="Lilith Taraschi" src="<%= asset_path 'lilith_t.jpg' %>">
						<h2>Lilith Taraschi</h2>
						<h4>Historian</h4>
						<p>Teramo (TE)<br>year 1996</p>  
					</div>
					
					<div class="member">
						<img alt="Davide Di Giacinto" src="<%= asset_path 'davide_dg.jpg' %>">
						<h2>Davide Di Giacinto</h2>
						<h4>Historian</h4>
						<p>Teramo (TE)<br>year 1995</p>
					</div>
					
					<div class="member">
						<img alt="Marco Matani" src="<%= asset_path 'marco_mat.jpg' %>">
						<h2>Marco Matani</h2>
						<h4>Historian</h4>
						<p>Teramo (TE)<br>year 1995</p>
					</div>
					
					<div class="member">
						<img alt="Alessia Coruzzi" src="<%= asset_path 'alessia_c.jpg' %>">
						<h2>Alessia Coruzzi</h2>
						<h4>Historian</h4>
						<p>Teramo (TE)<br>year 1996</p>
					</div>
					
					<div class="member">
						<img alt="Domenico Mattiucci" src="<%= asset_path 'domenico_m.jpg' %>">
						<h2>Domenico Mattiucci</h2>
						<h4>Historian</h4>
						<p>Bellante (TE)<br>year 1997</p>
					</div>
					
					<div class="member">
						<img alt="Michelangelo Ierace" src="<%= asset_path 'michelangelo_i.JPG' %>">
						<h2>Michelangelo Ierace</h2>
						<h4>Historian</h4>
						<p>Campli (TE)<br>year 1997</p>
					</div>
					
					<div class="member">
						<img alt="Federico Cioschi" src="<%= asset_path 'federico_c.jpg' %>">
						<h2>Federico Cioschi</h2>
						<h4>Historian</h4>
						<p>Teramo (TE)<br>year 1996</p>
					</div>
					
					<div class="member">
						<img alt="Pietro Oreglia" src="<%= asset_path 'pietro_o.jpg' %>">
						<h2>Pietro Oreglia</h2>
						<h4>Historian</h4>
						<p>Teramo (TE)<br>year 1995</p>
					</div>
				</div>
			</div>
			<!-- END chi siamo -->
			
			<!-- START credits -->
			<div class="credits">
				<div id="left_ftext">
					<b style="font-size: 1.35em;">Thanks to :</b><br>
					The Provincial Library "Melchiorre Delfico"<br>
					The online archive 'La stampa'<br>
					High School Albert Einstein - (TE) Abruzzo<br>
					2015 - Ragazzidel99
					<a href="mailto:info@ragazzidel99.it" style="color: #698888;">info@ragazzidel99.it</a>
				</div>
				<div id="connect">
					<div id="central_ftext"><b>CONNECT</b></div>
					<a href="https://www.facebook.com/pages/La-Grande-Guerra-in-tempo-reale/311104819049617?ref=ts&fref=ts">
						<img src="<%= asset_path 'Facebook-icon.png' %>">
					</a>
					<a href="https://twitter.com/lagrandeguerra">
						<img style="left:5%;" src="<%= asset_path 'Twitter-icon.png' %>">
					</a>
					<a href="https://github.com/lorenzo-camaione/Twistory3.0">
						<img src="<%= asset_path 'github.png' %>">
					</a>
					<a href="https://www.youtube.com/channel/UCoCqMnYaUqdHSel2e8Pr-_A">
						<img src="<%= asset_path 'Youtube-icon.png' %>">
					</a>
				</div>
				<div id="flogo">
					<img src="<%= asset_path 'ragazzidel99-logo.png' %>">
				</div>
			</div>
			<!-- END credits -->
			
		</div>
		<!-- END main div -->
		<script src="/assets/classie.js"></script>
		<script src="/assets/modalEffects.js"></script>
	<% end %>

app/views/feeds/index.html.erb
<%= content_for :head do %>
	
<% end %>

<%= content_for :body do %>
  <div class="background">
    <h1>I nostri feed</h1>
    <%= link_to 'Home', home_index_path %>
    <%= link_to 'New Feed', new_feed_path, :class => 'new_feed' %>
    <table>
      <thead>
        <tr>
          <th class="design">Testo</th>
          <th class="design">Text</th>
          <th class="design">Image</th>
          <th class="design">Date</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @feeds.each do |feed| %>
          <tr>
            <td class="feed"><%= feed.text_ita %></td>
            <td class="feed"><%= feed.text_eng %></td>
            <td class="feed"><%= image_tag(feed.image) %></td>
            <td class="feed"><%= feed.date.strftime('%d/%m/%Y %H:%M') %></td>
            <td class="buttons"><%= link_to 'Edit', edit_feed_path(feed) %></td>
            <td class="buttons"><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>
    <br>

<% end %>

app/views/feeds/new.html.erb
<%= content_for :head do %>
<% end %>

<%= content_for :body do %>
	<h1>Nuovo Feed</h1>

	<%= render 'form' %>

	<%= link_to 'Back', feeds_path %>
<% end %>

app/views/feeds/show.html.erb
<%= content_for :head do %>
	<title> Show </title>
<% end %>

<%= content_for :body do %>

<p>
  <strong>Text ita:</strong>
  <%= @feed.text_ita %>
</p>

<p>
  <strong>Text eng:</strong>
  <%= @feed.text_eng %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@feed.image) %>
</p>

<p>
  <strong>Date:</strong>
  <%= @feed.date %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>
<% end %>