config/routes.rb
Rails.application.routes.draw do
	get 'confirmation_page' => 'feeds#confirmation_page'
	get 'home/index' => 'feeds#home'
	resources :feeds
	resources :users, path: '/portal'
	resources :portals, path: '/#portal'
	
	devise_for :admins
	
	devise_scope :admin do
		authenticated :admin do
			get 'admins/sign_out' => 'devise/sessions#destroy'
		end

		unauthenticated do
			get 'admins/sign_in' => 'devise/sessions#new'
		end
	end
	
	devise_for :users, :controllers => { registrations: 'registrations' }
	
	devise_scope :user do
		authenticated :user do
			get '/users' => 'devise/registrations#edit'
			get 'users/sign_out' => 'devise/sessions#destroy'
			root to: "feeds#index", as: :authenticated_root
		end
		unauthenticated do
			get 'confirmation_page' => 'feeds#confirmation_page'
			get 'users/sign_in' => 'devise/sessions#new'
			get '/users' => 'devise/registrations#new'
			root to: 'feeds#home', as: :unauthenticated_root
		end
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :feeds
	mount_uploader :image, ImageUploader
	after_create :send_new_registration_email
	
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable, :confirmable,
		:recoverable, :rememberable, :trackable, :validatable

	validates :name, presence: true
		
	def send_new_registration_email
		UserMailer.new_registration_email(self).deliver_later
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_admin!

	def index
		@users = User.all
	end

	def show
	end
	
	def new
		@user = User.new
	end

	def edit
	end

	# POST /users
	# POST /users.json
	def create
		@user = User.new(user_params)

		respond_to do |format|
			if @user.save
				format.html { redirect_to @user, notice: 'User was successfully created.' }
				format.json { render :show, status: :created, location: @user }
			else
				format.html { render :new }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @user.update(user_params)
				format.html { redirect_to @user, notice: 'User was successfully updated.' }
				format.json { render :show, status: :ok, location: @user }
			else
				format.html { render :edit }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@user.destroy
		respond_to do |format|
			format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private

	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:email, :permissions)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<head>
	<title> Portal </title>
</head>

<body>
<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="field">
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :permissions %><br>
		<%= f.text_field :permissions %>
	</div>
	<div class="actions">
	<%= f.submit %>
	</div>
<% end %>
</body>

app/views/users/edit.html.erb
<% content_for :head do %>
	<title> Portal </title>
<% end %>

<% content_for :body do %>
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
<% end %>

app/views/users/index.html.erb
<% content_for :head do %>
	<title> Portal </title>
<% end %>
	
<% content_for :body do %>
<p id="notice"><%= notice %></p>
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th> email </th>
      <th> permission_level </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.permissions %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Feeds portal', portals_path %>

<% end %>

app/views/users/new.html.erb
<% content_for :head do %>
	<title> Portal </portal>
<% end %>

<% content_for :body do %>
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
<% end %>

app/views/users/show.html.erb
<% content_for :head do %>
	<title> Portal </title
<% end %>

<% content_for :body do %>
<p id="notice"><%= notice %></p>
<div>
	<strong>email:</strong>
	<%= @user.email %>
	<strong>permissions:</strong>
	<%= @user.permissions %>
</div>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<% end %>