config/routes.rb
Rails.application.routes.draw do
	get 'confirmation_page' => 'feeds#confirmation_page'
	get 'home/index' => 'feeds#home'
	resources :feeds
	resources :users, path: '/portal'
	resources :portals, path: '/#portal'
	
	devise_for :admins
	
	devise_scope :admin do
		authenticated :admin do
			get 'admins/sign_out' => 'devise/sessions#destroy'
		end

		unauthenticated do
			get 'admins/sign_in' => 'devise/sessions#new'
		end
	end
	
	devise_for :users, :controllers => { registrations: 'registrations' }
	
	devise_scope :user do
		authenticated :user do
			get '/users' => 'devise/registrations#edit'
			get 'users/sign_out' => 'devise/sessions#destroy'
			root to: "feeds#index", as: :authenticated_root
		end
		unauthenticated do
			get 'confirmation_page' => 'feeds#confirmation_page'
			get 'users/sign_in' => 'devise/sessions#new'
			get '/users' => 'devise/registrations#new'
			root to: 'feeds#home', as: :unauthenticated_root
		end
	end

end

app/controllers/portals_controller.rb
class PortalsController < ApplicationController
	before_action :authenticate_admin!
	before_action :set_portal, only: [:show, :edit, :update, :destroy]

	def index
		@portals = Feed.all
	end

	def show
	end

	def new
		@portal = Feed.new
	end

	def edit
	end

	def create
		# @portal = Feed.new(feed_params)
			# respond_to do |format|	
				# @portal.user_id = 100000000
				# if @portal.save
					# format.html { redirect_to @portal, notice: 'Feed was successfully created.' }
					# format.json { render :show, status: :created, location: @portal }
					# flash[:notice] = "Il feed è stato creato"
				# else
				# format.html { render :new }
				# format.json { render json: @portal.errors, status: :unprocessable_entity }
				# end
			# end
	end

	def update
		respond_to do |format| 
			if @portal.update(feed_params)
				format.html { redirect_to portals_path, notice: 'Feed was successfully updated.' }
				format.json { render :show, status: :ok, location: @portal }
			else
				format.html { redirect_to feeds_url }
				format.json { render json: @portal.errors, status: :unprocessable_entity }
				flash[:notice] = 'Non puoi modificare questo feed'
			end
		end
	end
	
	def destroy
		respond_to do |format|
			if @portal.destroy
				format.html { redirect_to portals_path, notice: 'Feed was successfully destroyed.' }
				format.json { head :no_content }
			else	
				format.html { redirect_to feeds_url }
				format.json { render json: @portal.errors, status: :unprocessable_entity }
				flash[:notice] = 'Non puoi distruggere questo feed'
			end
		end
	end

	private

	def set_portal
		@portal = Feed.find(params[:id])
	end

	def feed_params
		params.require(:portal).permit(:user_id, :text_ita, :text_eng, :image, :date, :publishing)
	end
end

app/helpers/portal_helper.rb
module PortalHelper
end

app/views/portals/_form.html.erb
<%= content_for :head do %>
<% end %>

<%= content_for :body do %>
	<%= form_for @portal, :as => :portal, :url => { :action => "update" } do |f| %>
	  <% if @portal.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@portal.errors.count, "error") %> prohibited this feed from being saved:</h2>
		  <ul>
		  <% @portal.errors.full_messages.each do |message| %>
		    <li><%= message %></li>
		  <% end %>
		  </ul>
		</div>
	  <% end %>

	  <div class="field">
		<%= f.label :text_ita %><br>
		<%= f.text_field :text_ita %>
	  </div>
	  <div class="field">
		<%= f.label :text_eng %><br>
		<%= f.text_field :text_eng %>
	  </div>
	  	  <div class="field">
		<%= f.label :publishing %><br>
		<%= f.check_box :publishing %>
	  </div>
	  <div class="field">
		<%= f.label :date %><br>
		<%= f.datetime_select :date %>
	  </div>
	  <div class="field">
		<%= f.file_field :feed_image %>
	  </div>
	  <div class="actions">
		<%= f.submit %>
	  </div>
	<% end %>
<% end %>

app/views/portals/edit.html.erb
<%= content_for :head do %>
	<title> Edit </title>
<% end %>

<%= content_for :body do %>
<h1> Editing Users </h1>
<%= render 'form' %>

<p id='notice'> <%= @error %> </p>
|
<%= link_to 'Back', portals_path %>

<% end %>

app/views/portals/index.html.erb
<%= content_for :head do %>
	<title> Main page </title>
<% end %>
<%= content_for :body do %>

<h1>Listing Feeds</h1>
<p id='notice'> <%= @error %> </p>
<p id='notice'> <%= notice %> </p>
<table>
  <thead>
    <tr>
      <th>User_email</th>
      <th>Text ita</th>
      <th>Text eng</th>
      <th>Image</th>
      <th>Date</th>
      <th>Is ita published</th>
      <th>Is eng published</th>
      <th>publishing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portals.each do |portal| %>
      <tr>
        <td><%= User.find(portal.user_id).email %></td>
        <td><%= portal.text_ita %></td>
        <td><%= portal.text_eng %></td>
        <td><%= portal.image %></td>
        <td><%= portal.date %></td>
        <td><%= portal.is_ita_published %></td>
        <td><%= portal.is_eng_published %></td>
        <td><%= portal.publishing %></td>
        <td><%= link_to 'Edit', edit_portal_path(portal) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'User settings', users_path %>
<% end %>

app/views/portals/new.html.erb
<%= content_for :head do %>
	<title> New </title>
<% end %>
<%= content_for :body do %>
<h1>New Feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>
<% end %>

app/views/portals/show.html.erb
<%= content_for :head do %>
	<title> Show </title>
<% end %>

<%= content_for :body do %>

  <strong>User_id:</strong>
  <%= @portal.user_id %>
</p>

<p>
  <strong>Text ita:</strong>
  <%= @portal.text_ita %>
</p>

<p>
  <strong>Text eng:</strong>
  <%= @portal.text_eng %>
</p>

<p>
  <strong>Image:</strong>
  <%= @portal.image %>
</p>

<p>
  <strong>Date:</strong>
  <%= @portal.date %>
</p>

<p>
  <strong>Is ita published:</strong>
  <%= @portal.is_ita_published %>
</p>

<p>
  <strong>Is eng published:</strong>
  <%= @portal.is_eng_published %>
</p>
<p>
  <strong>publishing:</strong>
  <%= @portal.publishing %>
</p>

<%= link_to 'Edit', edit_portal_path(@portal) %> |
<%= link_to 'Back', portals_path %>
<% end %>